server:
  port: 8084

spring:
  application:
    name: settlement-service

bank-service:
  base-url: http://localhost:8081

bank-account-service:
  base-url: http://localhost:8085

logging:
  level:
    dev.fisa: DEBUG